apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
          #    helm:
          #      releaseName: application-from-helm
          #      parameters:
          #        - name: "replicaCount"
          #          value: "3"
          #      valueFiles:
          #        - custom-values.yaml
    path: v03-argocd-applications/helm/nginx # path to our helm chart, having values.yml file
    repoURL: https://github.com/devopshobbies/argocd-tutorial.git # our get repository
    targetRevision: main # tells our branch
