apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: mattermost:final
          command: [ "python3", "mattermost.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "0.0.0.0"
          - name: token
            value: "b5fapmarcf8ejj4xmhmzky6hbc"
          - name: scheme
            value: "http"
          - name: port
            value: "8065"
          - name: channel_name
            value: "argocd-tutorial"
          - name: team_name
            value: "free-apps"
      restartPolicy: Never
  backoffLimit: 0
